version: '3.8'

volumes:
  postgres:

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=nitty_gritty
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports: ['5432:5432']
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 6s
        max_attempts: 2
        window: 60s
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      start_period: 6s
      interval: 3s
      retries: 6

  backend:
    image: node:18-alpine
    working_dir: /app
    volumes: [.:/app]
    user: 1000:1000
    environment:
      - DEBUG=off
    command: yarn start:dev
    depends_on:
      postgres: { condition: service_healthy }
    ports: ['3000:3000']
    deploy:
      replicas: 1
